#!/bin/bash

set -e

run_command() {
  echo "Running $1"
  bash -c "$1" 2>&1 &
  HAPROXY_PID="$!"
}

reload_conf() {
  haproxy_dns_cfg $DISCOVERY_URL > $HAPROXY_CONF || echo "Marathon is not available"
  echo "Reloading conf"
  run_command "haproxy -f $HAPROXY_CONF -sf $HAPROXY_PID"
}

onexit() {
  echo Sending SIGTERM to haproxy
  kill $HAPROXY_PID &>/dev/null
  sleep 1
}
trap onexit SIGINT SIGTERM EXIT

run_command "haproxy -f $HAPROXY_CONF"
while true; do reload_conf; sleep $RELOAD_TTL; done
